# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 8ix | Web Development blog
h1title: Web Development blog
email: andrew@8ix.co.uk
description: > # this means to ignore newlines until "baseurl:"
   Home of the web development topical blog for Andrew Yardley. Discussion and casting my opionion on the world that is web. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://8ix.co.uk" # the base hostname & protocol for your site
twitter_username: 8ix
github_username:  8ix

# Build settings
markdown: kramdown
