# Site settings
title: 8IX - Web Developer in Worcestershire
email: andrew@8ix.co.uk
description: I am based in Droitwich Worcestershire and have 8 years experience working across three creative agencies in Linux based web development using PHP / MYSQL / APACHE / NGINX / Node / CSS3 / HTML5.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://8ix.co.uk" # the base hostname & protocol for your site
twitter_username: 8ix
github_username:  8ix

# Build settings
markdown: kramdown
